# Generated by Django 4.2.1 on 2023-06-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=500)),
                ('address_2', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=300)),
            ],
        ),
    ]
